language: ruby
rvm:
   - 2.1
notifications:
  slack:
    secure: qkjxxj0NPwRb+ab3pHw0HAE2IfoTaadw1xIrx6U+oMHwPs/OwGE3mD0ou6Zc02Csl7wHap0egjqQwxI3sJvknXQzt0/mOKI/ygHx2lUmMB/eMbjEROSvTvMCBdhtaXKwpaieHlfFOMpM3Q9ApBMmNUqPZ4/OKVR6Yc44QI7YQKSET2mWIoB0QdXmPNsAFPs+3bON0c8ltKBZZCgTPrrgihSZgiLHflwZp1Y/b+lS3bikdqhGV5F11vL4dUtEgPtZeDdJ6GAJ5XU4Sh6Hw3hjUtOawzlPkbZw6jZsNC5Yo+SIeKwOPzru1PSzFgYYhGocmfAbZvXR01xy6KZ4pd+srE5dxZB5aMobG96gaz5xQs/vcVP6lB8OrUc+5wXOX6z7Mqy52C+lGw+5d5X8kQfF5w8zThQdq60d0mmQAvYIii3caR8sXEigWVVCLgrsQMpp7JHHI4bnBrUiJzlkmDfFVYYrpEau7JaxOdUoAScmypK2iOrbQau5oese9ozSa+a9rPwdvbIvBLW0FGk5hezMHggP091fxi+6xgu2+bNqrR+HCfk/iFboYGKeY6zNovPfdsc+SKny8gXQD3C5NpORqB15P88iURHYinnIpcrbWwR3KPV7Bgcxc8q2vBDw6kFgWQuEaKaxX5fcbrw5aKvtGHRot1cwDVG16U4GwYNCRiY=
